modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
logoFile = "icon.png"
displayURL="https://github.com/guncheque/sable-bridging"
issueTrackerURL="https://github.com/guncheque/sable-bridging/issues"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "sable"
    type = "optional"
    versionRange = "[2.0.3,)"
    ordering = "AFTER"
    side = "BOTH"
